---
title: Sja Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  writing:
    title: Writing
    output: true
defaults:    
- scope:
    path: ''
    type: works
  values:
    name:
    publication:
    date:
    url:
    featured: false
    layout: default
