---
title: Sam Anderson
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  archive:
    title: Writing
    output: true
    permalink: "/writing/:path/"
defaults:
- scope:
    path: ''
    type: archive
  values:
    Image: 
    Publication: 
    Source: http://google.com
