---
title: Sam Anderson
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  writing:
    title: Writing
    output: true
defaults:
- scope:
    path: ''
    type: writing
  values:
    name:
    magazine:
    featured: false
    layout: work
    source: http://google.com
